remote_theme: pmarsceill/just-the-docs

title: 数テロ改
description: 数テロ改のdescription
baseurl: "/mathterro"
url: "https://kampachi-percy.github.io"

lang: "ja"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/etc/", "docs/other"]

search_enabled: true

back_to_top: false

footer_content: |
  Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href="https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt" target="_blank" rel="noopener noreferrer">MIT license.</a><br>
  <a href="https://github.com/Kampachi-Percy/mathterro" target="_blank" rel="noopener noreferrer">Mathterro</a> is maintained by <a href="https://github.com/Kampachi-Percy" target="_blank" rel="noopener noreferrer">Kampachi-Percy</a>.

# Footer last edited timestamp
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
